spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/chuanqian/spring-cloud-config
          search-paths: respo
          username: 1178995389@qq.com
          password: "@zqc258zjy"

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/